apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  # local:
  #   push: false
  tagPolicy:
    sha256: {}
  artifacts:
    - image: eleft/auth
      context: auth
      custom:
        buildCommand: okteto build -t eleft/auth --cache-from eleft/auth
        dependencies:
          paths:
            - .
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .